@startuml

skinparam packageStyle rect

package main.de.kontext_e.jqassistant.plugin.plantuml.scanner {}
package main.de.kontext_e.jqassistant.plugin.plantuml.store.descriptor {}

main.de.kontext_e.jqassistant.plugin.plantuml.scanner <-- main.de.kontext_e.jqassistant.plugin.plantuml.store.descriptor

@enduml
