@startuml

skinparam packageStyle rect

class SomeClass
package scanner {}
package store {
    package descriptor {
        interface PlantUmlDescriptor
    }
}

scanner --> descriptor
SomeClass --> PlantUmlDescriptor

@enduml
